LIQUIDITY_EVENT_TYPES = frozenset({
    "LIQUIDITY_LEVEL", "LIQUIDITY_SWEEP",
})

LIQUIDITY_LEVEL_TYPES = frozenset({
    "CONFIRMED_SWING_HIGH", "CONFIRMED_SWING_LOW", "EQUAL_HIGH", "EQUAL_LOW",
    "PREVIOUS_DAY_HIGH", "PREVIOUS_DAY_LOW", "PREVIOUS_SESSION_HIGH",
    "PREVIOUS_SESSION_LOW", "CURRENT_SESSION_HIGH", "CURRENT_SESSION_LOW",
    "PREVIOUS_WEEK_HIGH", "PREVIOUS_WEEK_LOW", "PREVIOUS_MONTH_HIGH", "PREVIOUS_MONTH_LOW",
})

STRUCTURE_EVENT_TYPES = frozenset({
    "SWING_HIGH", "SWING_LOW", "HH", "HL", "LH", "LL", "EQUAL_HIGH", "EQUAL_LOW",
    "BULLISH_BOS", "BEARISH_BOS", "BULLISH_CHOCH", "BEARISH_CHOCH",
})
