"""Phase 8 paper trading audit store. Revision ID: 20260825_0011; Revises: 20260825_0010"""
from alembic import op
import sqlalchemy as sa
revision="20260825_0011";down_revision="20260825_0010";branch_labels=None;depends_on=None
def upgrade():
    op.create_table("paper_accounts",sa.Column("account_id",sa.String(64),primary_key=True),sa.Column("initial_balance",sa.Float,nullable=False),sa.Column("balance",sa.Float,nullable=False),sa.Column("equity",sa.Float,nullable=False),sa.Column("margin",sa.Float,nullable=False),sa.Column("free_margin",sa.Float,nullable=False),sa.Column("used_margin",sa.Float,nullable=False),sa.Column("realized_pnl",sa.Float,nullable=False),sa.Column("unrealized_pnl",sa.Float,nullable=False),sa.Column("commission",sa.Float,nullable=False),sa.Column("slippage",sa.Float,nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("paper_positions",sa.Column("position_id",sa.String(64),primary_key=True),sa.Column("symbol",sa.String(32),nullable=False),sa.Column("direction",sa.String(8),nullable=False),sa.Column("state",sa.String(32),nullable=False),sa.Column("opened_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("position_json",sa.JSON,nullable=False))
    op.create_table("paper_orders",sa.Column("order_id",sa.String(64),primary_key=True),sa.Column("position_id",sa.String(64)),sa.Column("symbol",sa.String(32),nullable=False),sa.Column("order_type",sa.String(16),nullable=False),sa.Column("timestamp",sa.DateTime(timezone=True),nullable=False),sa.Column("order_json",sa.JSON,nullable=False))
    op.create_table("paper_executions",sa.Column("id",sa.Integer,primary_key=True),sa.Column("order_id",sa.String(64)),sa.Column("timestamp",sa.DateTime(timezone=True),nullable=False),sa.Column("accepted",sa.Boolean,nullable=False),sa.Column("rejection_reason",sa.String(128)),sa.Column("execution_json",sa.JSON,nullable=False))
    op.create_table("paper_dca_events",sa.Column("dca_id",sa.String(64),primary_key=True),sa.Column("position_id",sa.String(64),nullable=False),sa.Column("timestamp",sa.DateTime(timezone=True),nullable=False),sa.Column("event_json",sa.JSON,nullable=False))
    op.create_table("paper_risk_events",sa.Column("id",sa.Integer,primary_key=True),sa.Column("timestamp",sa.DateTime(timezone=True),nullable=False),sa.Column("risk_state",sa.String(32),nullable=False),sa.Column("reason",sa.String(128)),sa.Column("event_json",sa.JSON,nullable=False))
    op.create_table("paper_trade_journal",sa.Column("trade_id",sa.String(64),primary_key=True),sa.Column("timestamp",sa.DateTime(timezone=True),nullable=False),sa.Column("journal_json",sa.JSON,nullable=False))
    op.create_table("paper_equity_snapshots",sa.Column("id",sa.Integer,primary_key=True),sa.Column("account_id",sa.String(64),nullable=False),sa.Column("timestamp",sa.DateTime(timezone=True),nullable=False),sa.Column("equity",sa.Float,nullable=False),sa.Column("balance",sa.Float,nullable=False),sa.Column("drawdown",sa.Float,nullable=False),sa.Column("snapshot_json",sa.JSON,nullable=False))
def downgrade():
    for table in ("paper_equity_snapshots","paper_trade_journal","paper_risk_events","paper_dca_events","paper_executions","paper_orders","paper_positions","paper_accounts"):op.drop_table(table)
