import{useEffect,useState}from'react';import{loadDashboard,loadEquity,Envelope}from'./api';
const TFS=['D1','H4','H1','M30','M15','M5'];
const value=(v:any,fallback:any='—')=>v===null||v===undefined||v===''?String(fallback):String(v);
function Status({label,state}:{label:string;state:string}){return <div className="status"><span>{label}</span><b className={`tone ${state.toLowerCase()}`}>{state}</b></div>}
function Panel({title,children,className=''}:{title:string;children:any;className?:string}){return <section className={`panel ${className}`}><h2>{title}</h2>{children}</section>}
function age(seconds:number|null|undefined){if(seconds===null||seconds===undefined)return 'AGE UNKNOWN';if(seconds<60)return `${Math.round(seconds)}s ago`;if(seconds<3600)return `${Math.round(seconds/60)}m ago`;return `${Math.round(seconds/3600)}h ago`}
function Fresh({env}:{env?:Envelope}){if(!env)return <span className="stale">DATA UNAVAILABLE</span>;const when=env.last_update?new Date(env.last_update).toLocaleTimeString():'NO SOURCE TIMESTAMP';return <span className={env.stale?'stale':'fresh'}>{env.stale?'STALE DATA':'LIVE'} · {when} · {age(env.data_age_seconds)}</span>}
export function App(){const[symbol,setSymbol]=useState('EURUSD');const[data,setData]=useState<Record<string,Envelope>>({});const[error,setError]=useState('');const[equity,setEquity]=useState<{timestamp:string;equity:number;drawdown:number}[]>([]);
 useEffect(()=>{let active=true;const run=()=>{loadDashboard(symbol).then(v=>{if(active){setData(v);setError('')}}).catch(()=>{if(active)setError('DATA UNAVAILABLE — dữ liệu cũ không được hiển thị như dữ liệu mới')});loadEquity().then(rows=>{if(active)setEquity(rows)}).catch(()=>{if(active)setEquity([])})};run();const id=setInterval(run,10000);return()=>{active=false;clearInterval(id)}},[symbol]);
 const overview=data.overview?.data||{};const market=data.market?.data||{};const mtf=data.mtf?.data||{};const liquidity=data.liquidity?.data||{};const indicators=data.indicators?.data||{};const ai=data.ai?.data||{};const strategy=data.strategy?.data||{};const risk=data.risk?.data||{};const positions=data.positions?.data||{};const performance=data.performance?.data||{};const journal=data.journal?.data||{};const alerts=data.alerts?.data||{};const timeline=data.timeline?.data||{};
 return <div className="shell"><header><div><p className="eyebrow">MARKET INTELLIGENCE · PAPER OBSERVATION</p><h1>ALM—TRADING <span>COMMAND CENTER</span></h1></div><div className="system-grid">{Object.entries(overview.system||{}).map(([k,v])=><Status key={k} label={k.replace('_',' ')} state={String(v)}/>)}</div><div className="env">ENVIRONMENT <b>PAPER</b></div></header>
 <aside><label htmlFor="symbol">SYMBOL</label><select id="symbol" value={symbol} onChange={e=>setSymbol(e.target.value)}>{(overview.symbols||['EURUSD']).map((s:string)=><option key={s}>{s}</option>)}</select><nav aria-label="Dashboard sections">{['Overview','MTF Matrix','Liquidity','Indicators','Neural Network','Strategy','Risk','Positions'].map(x=><a key={x} href={`#${x.toLowerCase().replaceAll(' ','-')}`}>{x}</a>)}</nav><div className="session"><small>SESSION</small><strong>{value(market.market_session,'UNAVAILABLE')}</strong></div></aside>
 <main>{error&&<div role="alert" className="error">{error}</div>}<div className="ticker" id="overview"><div><small>{symbol}</small><strong>{value(market.quote?.mid_price)}</strong></div><div>BID <b>{value(market.quote?.bid)}</b></div><div>ASK <b>{value(market.quote?.ask)}</b></div><div>SPREAD <b>{value(market.quote?.spread)}</b></div><Fresh env={data.market}/></div>
 <Panel title="MULTI—TIMEFRAME MATRIX" className="wide"><div className="alignment"><b>{value(mtf.alignment?.score,0)}%</b><span>{value(mtf.alignment?.status,'WAIT')}</span>{mtf.alignment?.conflict&&<em>TIMEFRAME CONFLICT</em>}</div><div className="tf-grid">{TFS.map(tf=>{const x=mtf.timeframes?.[tf]||{};return <article key={tf}><h3>{tf}</h3><strong>{value(x.trend,'UNAVAILABLE')}</strong><dl><dt>Structure</dt><dd>{value(x.structure)}</dd><dt>BOS</dt><dd>{value(x.bos)}</dd><dt>CHoCH</dt><dd>{value(x.choch)}</dd><dt>Swing H/L</dt><dd>{value(x.swing_high)} / {value(x.swing_low)}</dd></dl></article>})}</div></Panel>
 <Panel title="LIQUIDITY MAP"><Fresh env={data.liquidity}/><pre>{JSON.stringify(liquidity.timeframes?.M15||{status:'NO CONFIRMED SWEEP'},null,2)}</pre></Panel>
 <Panel title="INDICATORS · M15"><div className="metric-grid">{Object.entries(indicators.timeframes?.M15?.indicators||{RSI:'UNAVAILABLE',ADX:'UNAVAILABLE',Ichimoku:'UNAVAILABLE',ATR:'UNAVAILABLE'}).slice(0,8).map(([k,v])=><div key={k}><small>{k}</small><b>{value(v)}</b></div>)}</div><p className="notice">Indicators are supportive features — never standalone BUY/SELL signals.</p></Panel>
 <Panel title="NEURAL NETWORK"><Status label="MODEL" state={value(ai.model_status,'OFFLINE')}/><div className="probabilities">{['prob_up','prob_down','prob_neutral'].map(k=><div key={k}><span>{k.replace('prob_','').toUpperCase()}</span><progress max="1" value={ai.prediction?.[k]||0}/><b>{Math.round((ai.prediction?.[k]||0)*100)}%</b></div>)}</div><p>{value(ai.status_reason)}</p></Panel>
 <Panel title="STRATEGY DECISION" className="strategy"><div className="decision">{value(strategy.decision?.decision,'WAIT')}</div><div className="score">SCORE <b>{value(strategy.setup?.setup_score?.score,0)}/100</b></div><h3>DECISION EXPLANATION</h3><ul>{(strategy.decision?.reason_codes||['WHY WAIT — DATA UNAVAILABLE']).map((r:string)=><li key={r}>{r}</li>)}</ul></Panel>
 <Panel title="RISK MONITOR"><Status label="RISK STATE" state={value(risk.risk_state,'BLOCKED')}/><div className="metric-grid"><div><small>BALANCE</small><b>{value(risk.account?.balance)}</b></div><div><small>EQUITY</small><b>{value(risk.account?.equity)}</b></div><div><small>DAILY PNL</small><b>{value(risk.daily_pnl)}</b></div><div><small>MAX DD</small><b>{value(risk.account?.max_drawdown)}</b></div></div></Panel>
 <Panel title="PAPER POSITIONS" className="wide"><table><thead><tr><th>Symbol</th><th>Direction</th><th>Average Entry</th><th>Quantity</th><th>Unrealized PnL</th><th>DCA</th><th>State</th></tr></thead><tbody>{positions.items?.length?positions.items.map((p:any)=><tr key={p.position_id}><td>{p.symbol}</td><td>{p.direction}</td><td>{p.average_entry_price}</td><td>{p.quantity}</td><td>{p.unrealized_pnl}</td><td>{p.dca_entries}</td><td>{p.state}</td></tr>):<tr><td colSpan={7}>NO OPEN PAPER POSITIONS</td></tr>}</tbody></table></Panel>
 <Panel title="EQUITY · PERFORMANCE"><div className="chart" aria-label="Equity curve">{equity.length?<><svg viewBox="0 0 100 40" preserveAspectRatio="none" role="img" aria-label={`Equity curve, ${equity.length} points`}><polyline fill="none" stroke="currentColor" strokeWidth="1" points={equity.map((row,index)=>{const values=equity.map(item=>item.equity);const low=Math.min(...values);const high=Math.max(...values);const span=high-low||1;const x=equity.length>1?(index/(equity.length-1))*100:0;const y=40-((row.equity-low)/span)*38-1;return `${x.toFixed(2)},${y.toFixed(2)}`}).join(' ')}/></svg><dl className="equity-figures"><dt>POINTS</dt><dd>{equity.length}</dd><dt>LATEST</dt><dd>{equity[equity.length-1].equity}</dd><dt>MAX DD</dt><dd>{Math.max(...equity.map(row=>row.drawdown)).toFixed(4)}</dd></dl></>:<span>NO EQUITY HISTORY</span>}</div><pre>{JSON.stringify(performance.overall||{},null,2)}</pre></Panel>
 <Panel title="TRADE JOURNAL"><table><tbody>{journal.items?.length?journal.items.map((j:any)=><tr key={j.trade_id}><td>{j.trade_id}</td><td>{value(j.final_result?.net_pnl)}</td><td>{value(j.exit_reason)}</td></tr>):<tr><td>NO PAPER TRADES</td></tr>}</tbody></table></Panel>
 <Panel title="EVENT TIMELINE"><ol className="timeline">{timeline.items?.length?timeline.items.slice(0,8).map((e:any)=><li key={`${e.timestamp}-${e.type}`}><time>{new Date(e.timestamp).toLocaleTimeString()}</time><b>{e.type}</b></li>):<li>NO EVENTS</li>}</ol></Panel></main>
 <aside className="alerts"><h2>ALERT CENTER</h2><div className="alert-count"><b>{alerts.unread||0}</b> unread · <b>{alerts.critical||0}</b> critical</div>{alerts.items?.length?alerts.items.map((a:any)=><article key={a.alert_id} className={a.severity.toLowerCase()}><small>{a.severity} · {a.alert_type}</small><b>{a.title}</b><p>{a.message}</p></article>):<p>NO ACTIVE ALERTS</p>}</aside><footer>OBSERVATION ONLY · PAPER ENVIRONMENT · NO LIVE EXECUTION</footer></div>}
